baseURL = "https://akmnn.de"
languageCode = "de-DE"
title = "Henry Akmann"
rssLimit = 20
copyright = ""
minify = false

[Author]
  name = "akmann"
  email = "akmann.henry@gmail.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true